services:
  emqx:
    image: emqx/emqx-enterprise:6.2.2
    container_name: emqx
    ports:
      - "127.0.0.1:1883:1883"    # MQTT TCP
      - "8883:8883"    # MQTT SSL
      - "127.0.0.1:8083:8083"    # MQTT WS
      - "8084:8084"    # MQTT WebSockets SSL
      - "127.0.0.1:18083:18083"  # Dashboard UI
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
    restart: unless-stopped
    environment:
      EMQX_DASHBOARD__DEFAULT_PASSWORD: monicarovianadewi
volumes:
  emqx-data:
  emqx-log: